# Generated by Django 5.0.1 on 2024-01-21 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recevoir',
            old_name='id_utilisateur_1',
            new_name='id_utilisateur',
        ),
    ]
