# Generated by Django 5.0.1 on 2024-01-03 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_voyage_prix_voyage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='id_hotel',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='n_chambreDispo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='id_promotion',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.promotion'),
        ),
    ]
