# Generated by Django 5.0.1 on 2024-01-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_id_utilisateur_1_recevoir_id_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='content',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
