# Generated by Django 5.0.1 on 2024-01-22 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_notification_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recevoir',
            old_name='id_utilisateur',
            new_name='id_utilisateur_1',
        ),
    ]
