# Generated by Django 5.0 on 2024-01-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_id_utilisateur_recevoir_id_utilisateur_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='prenom_utilisateur',
            field=models.CharField(default='user_name1', max_length=15),
            preserve_default=False,
        ),
    ]
