# Generated by Django 5.0 on 2024-01-22 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_prenom_utilisateur_utilisateur_nom_utilisateur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aimer',
            old_name='id_utilisateur_1',
            new_name='id_utilisateur',
        ),
        migrations.RenameField(
            model_name='recevoir',
            old_name='id_utilisateur_1',
            new_name='id_utilisateur',
        ),
        migrations.RenameField(
            model_name='reservervoyage',
            old_name='id_utilisateur_1',
            new_name='id_utilisateur',
        ),
    ]
