# Generated by Django 5.0.1 on 2024-01-23 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_image_path_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='path_image',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
