# Generated by Django 5.0.1 on 2024-01-24 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_image_path_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservervoyage',
            name='id_vol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.vol'),
        ),
    ]
